import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from 'next-themes';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
  hero,
}: Readonly<{ children: React.ReactNode; hero: React.ReactNode }>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='antialiased'>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          {hero}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
