import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
  hero,
}: Readonly<{ children: React.ReactNode; hero: React.ReactNode }>) {
  return (
    <html lang="en" data-oid="-jftgca">
      <body className="antialiased" data-oid="6rxid9n">
        {hero}
        {children}
      </body>
    </html>
  );
}
